---
engines:

  pep8:
    enabled: true

  radon:
    enabled: true

  fixme:
    enabled: true

  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 35

ratings:
  paths:
  - "**.py"

exclude_paths:
  - hack_assembler/tests/**/*
